import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const testBuild = (process.argv[2] === "development");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["Source/Main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
  sourcemap: prod ? false : "inline",
  define: {
    __RENDER_CACHE_VERSION__: String(Math.floor(Math.random() * 1e9)),
    __EP_LOG_LEVEL__: prod ? String(4) : String(0),
  },
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else if (testBuild) {
  await context.rebuild();
	process.exit(0);
} else {
  await context.watch();
}
